import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <nav className="bg-slate-600 p-4 sticky top-0 drop-shadz" */}
      <body className="dark:bg-cyan-950	 ">
        <Navbar/> 
        {children}
      </body>
    </html>
  );
}
